export default {
	plugins: ['@typescript-eslint', 'import'],
	extends: [
		'plugin:import/typescript',
		'plugin:@typescript-eslint/eslint-recommended',
		'plugin:@typescript-eslint/recommended',
		'plugin:@typescript-eslint/recommended-requiring-type-checking',
	],
	rules: {
		'@typescript-eslint/array-type': 'error',
		'@typescript-eslint/ban-ts-comment': ['error', { 'ts-ignore': false }],
		'@typescript-eslint/brace-style': 'error',
		'@typescript-eslint/consistent-type-assertions': 'error',
		'@typescript-eslint/consistent-type-definitions': 'error',
		'@typescript-eslint/default-param-last': 'error',
		'@typescript-eslint/no-dupe-class-members': 'error',
		'@typescript-eslint/no-unused-expressions': ['error', { allowTernary: true }],
		'@typescript-eslint/prefer-for-of': 'error',
		'@typescript-eslint/prefer-function-type': 'error',
		'@typescript-eslint/prefer-includes': 'error',
		'@typescript-eslint/prefer-optional-chain': 'error',
		'@typescript-eslint/prefer-string-starts-ends-with': 'error',
		'@typescript-eslint/quotes': ['error', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
		'@typescript-eslint/return-await': 'error',
		'@typescript-eslint/semi': ['error', 'always'],
		'@typescript-eslint/no-inferrable-types': ['error', { ignoreProperties: true, ignoreParameters: true }],

		'@typescript-eslint/ban-types': [
			'warn',
			{
				types: { Function: { message: 'Avoid the Function type', fixWith: 'new (...args: any[]) => any' } },
				extendDefaults: false,
			},
		],
		'@typescript-eslint/class-literal-property-style': 'warn',
		'@typescript-eslint/comma-spacing': 'warn',
		'@typescript-eslint/explicit-function-return-type': ['warn', { allowExpressions: true }],
		'@typescript-eslint/indent': [
			'warn',
			'tab',
			{ SwitchCase: 1, FunctionDeclaration: { parameters: 'first' }, FunctionExpression: { parameters: 'first' } },
		],
		'@typescript-eslint/member-delimiter-style': [
			'warn',
			{ multiline: { delimiter: 'semi', requireLast: true }, singleline: { delimiter: 'semi', requireLast: false } },
		],
		'@typescript-eslint/member-ordering': [
			'warn',
			{
				default: [
					'static-field',
					'static-method',
					'abstract-field',
					'abstract-method',
					'instance-field',
					'constructor',
					'instance-method',
				],
			},
		],
		'@typescript-eslint/method-signature-style': ['warn', 'method'],
		'@typescript-eslint/no-explicit-any': ['warn', { ignoreRestArgs: true }],
		'@typescript-eslint/no-unnecessary-boolean-literal-compare': 'warn',
		'@typescript-eslint/no-unnecessary-qualifier': 'warn',
		'@typescript-eslint/no-unnecessary-type-arguments': 'warn',
		'@typescript-eslint/explicit-module-boundary-types': ['warn', { allowDirectConstAssertionInArrowFunctions: true }],
		'@typescript-eslint/no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none', ignoreRestSiblings: true }],
		'@typescript-eslint/no-use-before-define': 'warn',
		'@typescript-eslint/prefer-readonly': 'warn',
		'@typescript-eslint/restrict-plus-operands': ['warn', { checkCompoundAssignments: true }],
		'@typescript-eslint/space-before-function-paren': ['warn', { asyncArrow: 'always', anonymous: 'never', named: 'never' }],
		'@typescript-eslint/switch-exhaustiveness-check': 'warn',
		'@typescript-eslint/type-annotation-spacing': 'warn',
		'@typescript-eslint/typedef': [
			'warn',
			{
				arrowParameter: false,
				variableDeclarationIgnoreFunction: true,
				objectDestructuring: false,
				arrayDestructuring: false,
				memberVariableDeclaration: false,
			},
		],

		'@typescript-eslint/no-empty-function': 'off',
		'@typescript-eslint/no-empty-interface': 'off',
		'@typescript-eslint/no-non-null-assertion': 'off',
		'@typescript-eslint/no-unnecessary-type-assertion': 'off',

		'indent': 'off',
		'no-prototype-builtins': 'off',
		'no-return-await': 'off',
		'require-await': 'off',
		'require-jsdoc': 'off',
		'no-invalid-this': 'off',
	},
}
